# syntax=docker/dockerfile:1

# ---- Base ----
FROM node:20-alpine AS base
# Add libc6-compat for compatibility with some native modules on Alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# ---- Dependencies ----
# Install dependencies separately so this layer is cached as long as
# package.json / package-lock.json haven't changed.
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

# ---- Builder ----
# Rebuild source only when needed; reuses the cached deps layer above.
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during build (optional)
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ---- Runner ----
# Minimal production image using Next.js standalone output.
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=builder /app/public ./public

# Pre-create the .next dir with correct ownership for the cache
RUN mkdir .next && chown nextjs:nodejs .next

# Copy the standalone server bundle and static files
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# `server.js` is generated by `next build` when output is set to "standalone"
CMD ["node", "server.js"]
